# Copyright (c) 2023 Roberto Rossini (roberros@uio.no)
# SPDX-License-Identifier: MIT

name: Build fetch-and-sum-bench Dockerfile

on:
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/build-fetch-and-sum-bench*dockerfile.yml"
      - ".github/workflows/build-dockerfile.yml"
      - "containers/fetch-and-sum-bench*.Dockerfile"
      - "benchmarks/**"
      - "utils/**"
      - "CMakeLists.txt"
      - "conanfile.txt"
  pull_request:
    branches: [ main ]
    paths:
      - ".github/workflows/build-fetch-and-sum-bench*dockerfile.yml"
      - ".github/workflows/build-dockerfile.yml"
      - "containers/fetch-and-sum-bench*.Dockerfile"
      - "benchmarks/**"
      - "utils/**"
      - "CMakeLists.txt"
      - "conanfile.txt"

jobs:
  build-fetch-and-sum-bench-dockerfile:
    name: Build fetch-and-sum-bench Dockerfile
    uses: paulsengroup/2023-hictk-paper/.github/workflows/build-dockerfile.yml@main
    with:
      dockerfile-glob: "containers/fetch-and-sum-bench__*.Dockerfile"

    permissions:
      contents: read
      packages: write
