# Copyright (c) 2023 Roberto Rossini (roberros@uio.no)
# SPDX-License-Identifier: MIT

name: Build utils Dockerfile

on:
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/build-utils*dockerfile.yml"
      - ".github/workflows/build-dockerfile.yml"
      - "containers/utils*.Dockerfile"
  pull_request:
    branches: [ main ]
    paths:
      - ".github/workflows/build-utils*dockerfile.yml"
      - ".github/workflows/build-dockerfile.yml"
      - "containers/utils*.Dockerfile"

jobs:
  build-utils-dockerfile:
    name: Build utils Dockerfile
    uses: paulsengroup/2023-hic2cool-ng-paper-benchmarks/.github/workflows/build-dockerfile.yml@main
    with:
      dockerfile-glob: "containers/utils*.Dockerfile"

    permissions:
      contents: read
      packages: write
