# Copyright (c) 2023 Roberto Rossini (roberros@uio.no)
# SPDX-License-Identifier: MIT

name: Build hic-tools Dockerfile

on:
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/build-hic-tools*dockerfile.yml"
      - ".github/workflows/build-dockerfile.yml"
      - "containers/hic-tools*.Dockerfile"
      - "utils/4dn_pairs_to_txt/**"
      - "utils/CMakeLists.txt"
  pull_request:
    branches: [ main ]
    paths:
      - ".github/workflows/build-hic-tools*dockerfile.yml"
      - ".github/workflows/build-dockerfile.yml"
      - "containers/hic-tools*.Dockerfile"
      - "utils/4dn_pairs_to_txt/**"
      - "utils/CMakeLists.txt"

jobs:
  build-hic-tools-dockerfile:
    name: Build hic-tools Dockerfile
    uses: paulsengroup/2023-hictk-paper/.github/workflows/build-dockerfile.yml@main
    with:
      dockerfile-glob: "containers/hic-tools__*.Dockerfile"

    permissions:
      contents: read
      packages: write
